{% set name = "pelicanfs" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pelicanfs-{{ version }}.tar.gz
  sha256: 0f67b1bfa115b6249a6cf808476925590fe18ce3433f637da6b0c0ead55bc1d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - aiohttp >=3.9.4,<3.10.dev0
    - aiosignal >=1.3.1,<1.4.dev0
    - async-timeout >=4.0.3,<4.1.dev0
    - attrs >=23.2.0,<23.3.dev0
    - cachetools >=5.3,<6.dev0
    - frozenlist >=1.4.1,<1.5.dev0
    - fsspec >=2024.3.1,<2024.4.dev0
    - idna >=3.7,<4.dev0
    - multidict >=6.0.5,<6.1.dev0
    - python >={{ python_min }},<4.0
    - yarl >=1.9.4,<1.10.dev0

test:
  requires:
    - pip
    - pytest
    - pytest-httpserver
    - trustme
    - python {{ python_min }}
  source_files:
    - test/
  commands:
    - python -m pip check
    - python -m pytest -ra -v test/

about:
  home: https://github.com/PelicanPlatform/pelicanfs
  summary: An FSSpec Implementation using the Pelican System
  dev_url: https://github.com/PelicanPlatform/pelicanfs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
