{% set name = "pelicanfs" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pelicanfs-{{ version }}.tar.gz
  sha256: 0f67b1bfa115b6249a6cf808476925590fe18ce3433f637da6b0c0ead55bc1d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - aiohttp >=3.9.4,<4.0.0a0
    - aiowebdav >=0.1.0rc5
    - cachetools >=5.3,<6.0.0a0
    - fsspec >=2024.3.1
    - python >={{ python_min }},<4

test:
  requires:
    - pip
    - pytest
    - pytest-httpserver
    - python {{ python_min }}
    - trustme
  source_files:
    - test/
  commands:
    - python -m pip check
    - python -m pytest -ra -v test/

about:
  home: https://github.com/PelicanPlatform/pelicanfs
  summary: An FSSpec Implementation using the Pelican System
  dev_url: https://github.com/PelicanPlatform/pelicanfs
  license: Apache-2.0
  license_file: LICENSE
  description: |
    PelicanFS is a file system interface (fsspec) for the Pelican Platform.
    For more information about pelican, see our
    [main website](https://pelicanplatform.org) or
    [Github page](https://github.com/PelicanPlatform/pelican).
    For more information about fsspec, visit the
    [filesystem-spec](https://filesystem-spec.readthedocs.io/en/latest/index.html)
    page.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
